lsi: false
safe: true
source: [/home/victor/Desktop/automatisering-binnenverlichting]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
